# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const creator = context.payload.sender.login
            console.log(context.payload.pull_request._links.review_comments);
            console.log(context.payload.pull_request._links.review_comment);
            console.log(context.payload.pull_request);

            const reviewComment0 = await github.request(`${context.payload._links.review_comments}/1`);
            const reviewComment1 = await github.request(`${context.payload._links.review_comments}/0`);
            console.log('0 :', reviewComment0);
            console.log('1 :', reviewComment1);



        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
